-- MySQL Script generated by MySQL Workbench
-- Fri Feb 28 13:20:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema taskmanagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taskmanagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taskmanagement` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `taskmanagement` ;

-- -----------------------------------------------------
-- Table `taskmanagement`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskmanagement`.`employees` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taskmanagement`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskmanagement`.`projects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taskmanagement`.`project_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskmanagement`.`project_employees` (
  `project_id` INT(11) NULL DEFAULT NULL,
  `emp_id` INT(11) NULL DEFAULT NULL,
  UNIQUE INDEX `UK_5u1xxy259w15rdhgpbsb09uub` (`emp_id` ASC) VISIBLE,
  INDEX `FKt9kxewjtx1iqoxwasi3ma5e0t` (`project_id` ASC) VISIBLE,
  CONSTRAINT `FKc0kj2miw0ex44slpx9bkh94gu`
    FOREIGN KEY (`emp_id`)
    REFERENCES `taskmanagement`.`employees` (`id`),
  CONSTRAINT `FKt9kxewjtx1iqoxwasi3ma5e0t`
    FOREIGN KEY (`project_id`)
    REFERENCES `taskmanagement`.`projects` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taskmanagement`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskmanagement`.`tasks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `task_desc` VARCHAR(45) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taskmanagement`.`project_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskmanagement`.`project_tasks` (
  `project_id` INT(11) NULL DEFAULT NULL,
  `task_id` INT(11) NULL DEFAULT NULL,
  UNIQUE INDEX `UK_6xal5xc3k6jhjo3xbppaprdbc` (`task_id` ASC) VISIBLE,
  INDEX `FKhsx8wvsrs7t8x9hq10jncbisx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `FKhsx8wvsrs7t8x9hq10jncbisx`
    FOREIGN KEY (`project_id`)
    REFERENCES `taskmanagement`.`projects` (`id`),
  CONSTRAINT `FKpd6ia2hqhwagm7ww99rjuro4e`
    FOREIGN KEY (`task_id`)
    REFERENCES `taskmanagement`.`tasks` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taskmanagement`.`task_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskmanagement`.`task_employees` (
  `emp_id` INT(11) NULL DEFAULT NULL,
  `task_id` INT(11) NULL DEFAULT NULL,
  UNIQUE INDEX `UK_1kln9v9lsthetlifu4toxu573` (`emp_id` ASC) VISIBLE,
  INDEX `FKms47t15vw89j10ptrbkwfrkpr` (`task_id` ASC) VISIBLE,
  CONSTRAINT `FK6svqkiyinepxm0oujqo090tyg`
    FOREIGN KEY (`emp_id`)
    REFERENCES `taskmanagement`.`employees` (`id`),
  CONSTRAINT `FKms47t15vw89j10ptrbkwfrkpr`
    FOREIGN KEY (`task_id`)
    REFERENCES `taskmanagement`.`tasks` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
